name: www

on:
  workflow_dispatch:

  schedule:
    # UTC 15:30 -> JST 00:30
    - cron:  "30 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Run a generate www"
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          echo "w" >> README.md
          git add README.md
          git commit -m ':octocat: www'
          git push origin main
